Mox.defmock(Bank.EventStoreMock, for: Bank.EventStore)
Mox.defmock(Bank.EventPublisherMock, for: Bank.EventPublisher)
Mox.defmock(Bank.AccountReadModelMock, for: Bank.AccountReadModel)
Mox.defmock(Bank.CommandHandlerMock, for: Bank.CommandHandler)
Mox.defmock(Bank.ProcessManagerMock, for: Bank.ProcessManager)
